import {
  Code2,
  Database,
  FileCode,
  Palette,
  Code,
  CodeIcon,
  Terminal,
  SquareTerminal,
  PhoneCall,
  Code2Icon,
  ToolCase,
  ImageDown,
  Brackets,
  Keyboard,
  FileType,
  BrushCleaning,
  FileText,
  RadioTower,
  Webhook,
  Heading1,
  GitPullRequest,
  Server,
} from "lucide-react";

export const techIcons: Record<string, { Icon: any; color: string }> = {
  Python: { Icon: SquareTerminal, color: "text-blue-500" },
  Django: { Icon: Server, color: "text-emerald-500" },
  DRF: { Icon: CodeIcon, color: "text-red-500" },
  PostgreSQL: { Icon: Database, color: "text-blue-500" },
  Swagger: { Icon: PhoneCall, color: "text-emerald-500" },
  React: { Icon: Code2Icon, color: "text-blue-500" },
  TypeScript: { Icon: FileCode, color: "text-cyan-500" },
  Vite: { Icon: ToolCase, color: "text-purple-500" },
  Tailwind: { Icon: Palette, color: "text-cyan-500" },
  OpenCV: { Icon: ImageDown, color: "text-red-500" },
  NumPy: { Icon: Brackets, color: "text-blue-500" },
  PyAutoGUI: { Icon: Keyboard, color: "text-zinc-400" },
  Tesseract: { Icon: FileType, color: "text-emerald-500" },
  SQLite: { Icon: Database, color: "text-blue-500" },
  Bootstrap: { Icon: BrushCleaning, color: "text-purple-500" },
  ReportLab: { Icon: FileText, color: "text-yellow-500" },
  JavaScript: { Icon: Code, color: "text-yellow-500" },
  jQuery: { Icon: Terminal, color: "text-blue-500" },
  Requests: { Icon: RadioTower, color: "text-emerald-500" },
  "Spoonacular API": { Icon: Webhook, color: "text-emerald-500" },
  Docker: { Icon: Code2, color: "text-blue-400" },
  HTML: { Icon: Heading1, color: "text-orange-500" },
  CSS: { Icon: BrushCleaning, color: "text-purple-500" },
  Git: { Icon: GitPullRequest, color: "text-purple-500" },
};
